version: '3.3'
services:
  mariadb:
    image: mariadb:10.7
    restart: unless-stopped
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=security_motion_tracker
      - TZ=Europe/Berlin
    ports:
    - 3306:3306
    
    volumes:
      - securitytracker-sql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: unless-stopped
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    
    ports:
      - 8888:80

    links:
      - mariadb

    environment:
      - PMA_HOST=mariadb

  app:
    image: carlkuhligk/securitymotiontracker:debug
    container_name: securitytracker
    restart: unless-stopped

    ports:
    # website
      - 80:80
    # websocket
      - 8080:8080

    links:
      - mariadb

    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Berlin

volumes:
  securitytracker-sql-data:
