<?php
# responselist
define("RP_NOT_CONNECTED", 1);
define("RP_CONNECTED", 2);
define("RP_GOBAL_UPDATE", 4);

define("RP_DEVICE_REGISTERED", 10);
define("RP_OBSERVER_REGISTERED", 11);
define("RP_OBSERVER_UNREGISTERED", 12);

define("RP_MISSING_API_KEY", 19);
define("RP_INVALID_API_KEY", 20);
define("RP_DEVICE_ALREADY_REGISTERED", 21);
define("RP_DEVICE_NOT_REGISTERED", 22);
define("RP_INVALID_DEVICE_ID", 23);
define("RP_OBSERVER_ALREADY_REGISTERED", 24);
define("RP_OBSERVER_NOT_REGISTERED", 25);
define("RP_MISSING_DEVICE_ID", 26);
define("RP_OBSERVER_MISSING_REGESTRATION_STATE", 27);
define("RP_OBSERVER_CANT_REGISTER_AS_DEVICE", 28);
define("RP_DEVICE_CANT_REGISTER_AS_OBSERVER", 29);
define("RP_MISSING_TYPE", 30);
define("RP_MISSING_DATA", 31);
define("RP_UNKNOWN_DATA_TYPE", 32);

define("RP_SERVER_OFFILNE", 40);
define("RP_UNKNOWN_ERROR", 42);
