# Rechte für `web_socket_server`@`%`
GRANT USAGE ON *.* TO `web_socket_server`@`%` IDENTIFIED BY PASSWORD '*8FE2D81F56B44DD37A276E5A077806A683D35B48';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `security\_motion\_tracker`.* TO `web_socket_server`@`%`;