-- useraccount
GRANT USAGE ON *.* TO `security_service`@`%` IDENTIFIED BY PASSWORD '*BE1143808127C38B85463E705873E98EF2483236';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `security\_tracker`.* TO `security_service`@`%`;
